config/routes.rb
Hadhada::Application.routes.draw do

  root  :to=>'main#index'

    resources :article,:except=>[:show] do
       collection do
         get :new_article
         post :create_article
         get :add_icon
         post :icon
       end
    end

    resources :comment do
      collection do
        post :create_comment
      end
    end

    resources :dashboard do
       collection do
         get :add_user
         post :create_user
       end
    end
get '/login', :to => 'main#sign', via: :get
    resources :main do
       collection do
         get :sign
         post :sign_in
         get :signup
         post :sign_up
         get :sign_out
         post :check_email
         post :check_username
       end
    end

    resources :category do
       collection do
       end
    end

    resources :sound do
       collection do
        get :sounds
       end
    end

    resources :quote do
       collection do
       end
    end

    resources :planer do
      collection do
      end
    end

  match '/planer/download/:filename', :action => 'download', :via => [:get], :controller => 'planer'
  match '/:category/:article/:id', :action => 'show', :via => [:get], :controller => 'article'

  match '*a', :to => 'application#routing', via: :get
  get '/404', :to => 'application#routing', via: :get
  get '/500', :to => 'application#server', via: :get
  

end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index
		arts=[]
		Article.all.each do |art|
			if art.category_id!=7 && arts.length < 4
				arts<<art
			end
		end
		@articles=arts
		@brain=Article.where(:category_id=>7).first
	end

	def sign
		if @user
			flash[:info]="تم تسجيل الدخول سابقا"
			redirect_to dashboard_index_path and return
		else
		render :layout => 'content_layout'
		end
	end

	def sign_in
		@user=User.where(:username=>params[:user][:username].downcase,:encrypted_password=>Digest::MD5.hexdigest(params[:user][:password]+"hadhada")).first
		if @user
			session[:user_id]=@user.id
			redirect_to dashboard_index_path
		else
			flash[:alert]="خطأ في اسم المستخدم او كلمة المرور"
			redirect_to sign_main_index_path and return
		end
	end

	def sign_out
		clear_session
		@user=nil
		flash[:info]="تم الخروج"
		redirect_to sign_main_index_path
	end

	def check_email
    	exists = false
    	if email = params[:email].downcase
    	  	exists = User.where(:email => email).exists?
    	end
    	
    		if exists
    	  		render :text => 'already taken', :status => 203 and return
    		else
    	  		render :text => "available", :status => 202 and return
    		end
    end

    def check_username
    	exists = false
    	if username = params[:username].downcase
    	  		exists = User.where(:username => username).exists?
    	end
	
	    	if exists
	    	  render :text => 'already taken', :status => 203 and return
	    	else
	    	  render :text => "available", :status => 202 and return
    		end
    end  
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<section class="camera_container">
        <div id="camera" class="camera_wrap center bg-general" style="display: block; height: 450px;">
          <div class="camera_fakehover">

            <div class="camera_target_content">
              <div class="cameraContents">
                <div class="cameraContent">
                <div class="camera_caption" style="visibility: visible; opacity: 1;">
              <div>

              <div class="bg_sec3" style="visibility: hidden;">
                <h2>
                  لماذا هدهدة؟
                </h2>
                <p>
                 ان تنشئة الاطفال بقدر ما هو موضوع عميق وعلمي ويحتاج للكثير من الوعي وله اثار تبق طويلا مع الطفل ،الا ان اساليبه بسيطة وغير معقدة وفطرية بالاساس! مثل  الهدهدة ..الهدهدة اغنية بسيطة وحركة خفيفة إلا انها تعزز مناعة الاطفال وتنمي دماغهم وتشفي بعض الامهم..
كل ما زاد التواصل والفهم للطفل وعشت لحظات الهدهدة بما تحمله من معاني حب وقرب وحنان وامان وتواصل موسيقي ، كل ما كانت عملية التربية اخف حملا واقل تحديات عندك من غيرها من الناس. هذه رسالتنا هنا في هدهدة، نبثها في محتوى عربي علمي فريد من نوعه على شبكة الانترنت.
                </p>
              </div>
            </div></div>
          <div class="col-sm-6 col-md-6 pull-right" id="family">
               <!--  <img class="img-responsive"src="/assets/banner-1.png" style="position: relative;top: 13.4em;"> -->
      <img src="/assets/logo.png" width="370" height="370" style="visibility: hidden;" id="logo" >
                </div>
          </div></div></div></div></div>
</section>
</div><section id="services" style="visibility: hidden;">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2 class="section-heading">آخر المقالات</h2>
                    <br/>
                    <br/>
                </div>
            </div>
        <div class="row text-center">
          <%if @articles!=nil%>
          <% @articles.each do |art|%>
        <div class="col-sm-6 col-md-3">
          <div class="thumbnail pad-0" style="background-color:<%=art.color%>;border: 1px solid <%=art.color%>;">
            <img src='<%="/images/#{art.id}.png" rescue " "%>' class="img-responsive">
              <div class="caption" style="color:#fff;">
                <%if art.title.length>30%>
                <h3 style="min-height: 45px;"><%=art.title.first(28)%> ...</h3>
                <%else%>
                <h3 style="min-height: 45px;"><%=art.title.first(30)%></h3>
                <%end%>
                <%if art.content.length>33%>
                <p> <%=art.content.first(30).html_safe %>...</p>
                <%else%>
                <p><%= art.content.html_safe %></p>
                <%end%>
              <a href="/<%= art.category.name.split(' ').join('-')%>/<%= art.title.split(' ').join('-')%>/<%=art.id%>" class="btn btn-md btn-secondary btn-xs" role="button">اقراء المزيد</a>
            </div>
          </div>
        </div>
        <%end%>
        <%end%>
        </div>
        </div>
    </section>
    
        <% if @brain != nil%>
        <section class="bg-2">
        <div class="container pad-bot">
            <div class="row">
                <div class="grid_12">
                    <div class="w3">
                      <%if @brain.title.length>120%>
                          <div class="title-1"><%=@brain.title.first(118)%> ..</div>
                      <%else%>
                          <div class="title-1"><%=@brain.title%></div>
                      <%end%>
                      <%if @brain.content.length>140%>
                        <div class="text-2"><%=@brain.content.first(137).html_safe %>...</div>
                      <%else%>
                        <div class="text-2"><%= @brain.content.html_safe %></div>
                      <%end%>
                    <a href="/<%= @brain.category.name.split(' ').join('-')%>/<%= @brain.title.split(' ').join('-')%>/<%=@brain.id%>" class="btn btn-md btn-brain" role="button">اقراء المزيد</a>
                    </div>
                </div>
            </div>
        </div>
      </section>
      <% end %>
<style type="text/css">
.bg-2 {
    background: #ffffff url(/assets/bg-1.png) 100% bottom no-repeat;
    color: #000000;
    height: 425px;
    background-position-x: 100%;
    background-position-y: 62%;
    background-size: 57%;
    margin-top: 30px;
}
.bg-2 .pad-bot {
    padding-bottom: 134px;
}
.grid_12 {
    width: 1170px;
}
.w3 {
    width: 64%;
    float: left;
}
.bg-2 .title-1 {
    color: #96CC5B;
    padding-bottom: 30px;
}
.title-1 {
    font-size: 60px;
    line-height: 71px;
    padding-top: 51px;
}
.bg-2 .text-2 {
    width: 91%;
}
.text-2 {
    font-size: 17px;
    line-height: 26px;
}
.btn-brain{
    color: #393030;
    background: #FFFFFF;
    border-color: #393030;
    padding: 10px 15px 10px;
}
.btn-brain:hover, .btn-brain:active {
    background: #96CC5B;
    border-color: #fff;
    color: #fff;
}
@media (max-width: 768px){
.bg-2 {
    background: #ffffff url(/assets/bg-1-1.png) right bottom no-repeat;
}
.bg-2 .pad-bot {
    padding-bottom: 134px;
}
.grid_12 {
    width: 100%;
}
.w3 {
    width: 100%;
    background: url(/assets/opac-1.png) 0 0 repeat;
}
.title-1 {
    font-size: 50px;
    line-height: 52px;
}
.btn-brain{
    margin-right: 35%;
    margin-bottom: 2%;
}
}
</style>
    <section>
      <div class="container">
        <div class="row">
            <div class="col-sm-6 text-center">
                <img src="/quotes/quote.png" id="quote">
            </div>
            <div class="col-sm-6">
              <a href="<%= sound_index_path%>">
              <img src="/assets/331.png" id="sound">
              <h3 class="qs">هدهدات</h3>
              </a>
            </div>

        </div>
      </div>
    </section>

    <div class="push"></div>
 <!-- Footer -->
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-left">
                <span class="copyright text-muted">Copyright &copy; 
                    <a href="#" target="_blank">
                    <b>Hadhada</b>
                    </a> 2016</span>
                </div>
                <div class="col-md-6 text-right">
                  <div class="social-area pull-right">                
                    <a class="btn btn-social btn-facebook btn-simple" href="#" target="_blank">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                    <a class="btn btn-social btn-twitter btn-simple" href="#" target="_blank">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-social btn-instagram btn-simple" href="#" target="_blank">
                        <i class="fa fa-instagram"></i>
                    </a>
                </div>
                </div>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="/assets/mainer.js"></script>

<script>
    $(window).scroll(function() {
        $('#cats').each(function(){
        var imagePos = $(this).offset().top;

        var topOfWindow = $(window).scrollTop();
            if (imagePos < topOfWindow+370) {
                $(this).addClass("animated fadeInUp");
                $(this).attr('style','visibility: visible;');
            }
        });
        $('#services').each(function(){
        var imagePos = $(this).offset().top;

        var topOfWindow = $(window).scrollTop();
            if (imagePos < topOfWindow+350) {
                $(this).addClass("animated fadeInUp");
                $(this).attr('style','visibility: visible;');
            }
        });
        $('#logo').each(function(){
        var imagePos = $(this).offset().top;

        var topOfWindow = $(window).scrollTop();
            if (imagePos < topOfWindow+350) {
                $(this).addClass("animated bounceInRight");
                $(this).attr('style','visibility: visible;');
            }
        });
        $('.bg_sec3').each(function(){
        var imagePos = $(this).offset().top;

        var topOfWindow = $(window).scrollTop();
            if (imagePos < topOfWindow+350) {
                $(this).addClass("animated bounceInLeft");
                $(this).attr('style','visibility: visible;');
            }
        });
    });
</script>

<style type="text/css">
.qs{
    margin-top: -14px;
    font-size: 40px;
    text-align: center;
    color: #56607D;
    letter-spacing: 1.2px;
}
.hads{
    position: absolute;
    top: 7.5em;
    right: -1.7em;
    z-index: 200;
    color: #FDDE46;
    font-size: 40px;
    letter-spacing: 1.4px;
}
#logo{
  position: relative;top: 3.2em;right: 8em;
}

.btn-lg{padding: 4px 25px; margin-top: 7px;}

.panel {
    box-shadow: 0 2px 0 rgba(0,0,0,0.075);
    border-radius: 50%;
    border: 0;
    margin-bottom: 15px;
    color: #fff;
    position: relative;
    top: 10em;
    z-index: 10;
    max-height: 192px;
    max-width: 188px;
    margin-right: 20px;
}


/*#F3004E mama tktob*/
/*om jadeda #BCF749*/
/*trjmat rgb(245, 116, 4)*/
/*rde3e #34BBAF*/

@media (min-width: 768px) {
.panel:hover{
     -moz-transform: scale(1.06);
  -webkit-transform: scale(1.06);
  -o-transform: scale(1.06);
  transform: scale(1.06);
}
#services .col-md-3:hover {
-moz-transform: scale(1.06);
  -webkit-transform: scale(1.06);
  -o-transform: scale(1.06);
  transform: scale(1.06);
}
#services .col-md-3 .thumbnail{min-height: 360px;max-height: 360px;}
#services .col-md-3{
  float: right;
}
}
@media (max-width: 768px) {
  #family{display: none;}
  #cats{
    position: relative;
    display: block;
    margin-bottom: 40px;
  }
  .panel {
    box-shadow: 0 2px 0 rgba(0,0,0,0.075);
    border-radius: 50%;
    border: 0;
    margin-bottom: 15px;
    color: #fff;
    position: relative;
    top: 3em;
    right: 13%;
    z-index: 10;
    max-height: 192px;
    max-width: 200px;
}
}
.panel>:last-child {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.panel .panel-heading, .panel>:first-child {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.panel-body {
    padding: 25px 20px;
}
.mar-btm {
    margin-bottom: 8px;
}
.text-sm {
    font-size: 26px;
}
.panel:hover img {
  -moz-transform: scale(1.1);
  -webkit-transform: scale(1.1);
  -o-transform: scale(1.1);
  transform: scale(1.1);
}
.panel img {
  -webkit-transition: all 220ms ease-in-out;
  -moz-transition: all 220ms ease-in-out;
  -o-transition: all 220ms ease-in-out;
  transition: all 220ms ease-in-out;
  width: 50px;
  margin-top: 0px;
}
.panel .btn{margin-top: 15px;}

.panel {
  -webkit-transition: all 220ms ease-in-out;
  -moz-transition: all 220ms ease-in-out;
  -o-transition: all 220ms ease-in-out;
  transition: all 220ms ease-in-out;
}

#services .col-md-3 {
    -webkit-transition: all 220ms ease-in-out;
  -moz-transition: all 220ms ease-in-out;
  -o-transition: all 220ms ease-in-out;
  transition: all 220ms ease-in-out;

}

#services .col-md-3:hover .thumbnail{
  border: 1px solid rgba(102, 102, 102, 0.52);
}

.thumbnail>img {
    max-height: 180px;
    min-height: 180px;
    min-width: 250px;
}
</style>

app/views/main/signup.html.erb
<% @page_title = "SignUp" %>
<div class="fullscreen-bg"></div>
<div id="signinn">
<div class="container">

<div class=" col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3 ">
<div class="admin-form theme-primary mw1000 center-block" style="padding-bottom: 100px;">

   <div class="panel heading-border panel-primary">
  <%= form_for(@user,:url=>sign_up_main_index_path,:html => {:id => "user"}) do |f| %>
            <div class="panel-heading">
                  <h3 class="panel-title" style="font-size:1.5em;">مستخدم جديد</h3>
            </div>

            <label for="username" class="field prepend-icon">
      <%= f.text_field :username, :class=>"form-control",
          :required=>"true",:placeholder=>"إسم المستخدم" ,:id=>"username"%>
          <label for="username" class="field-icon">
              <i class="fa fa-user"></i>
          </label>

          </label>

          <br>
          <br>

  <label for="email" class="field prepend-icon">
    <%= f.text_field :email,:class=>"form-control",:placeholder=>"البريد الالكتروني", :required=>"true",:id=>"signup-email"%> 
    <label for="email" class="field-icon">
              <i class="fa fa-envelope"></i>
          </label>
          </label>

          <br>
          <br>


    <label for="password" class="field prepend-icon">
    <%= f.password_field :password,:id=>"pass",:class=>"form-control" ,:placeholder=>"كلمة المرور", :required=>"true",:id=>"signup-pass"%>
    <label for="password" class="field-icon">
              <i class="fa fa-lock"></i>
          </label>
          </label>

          <br>
          <br>




    <label for="password_confirmation" class="field prepend-icon">
    <%= f.password_field :password_confirmation,:class=>"form-control" ,:placeholder=>"تأكيد كلمة المرور", :required=>"true",:id=>"pass_confirm"%>
    <label for="password_confirmation" class="field-icon">
              <i class="fa fa-check"></i>
          </label>
          </label>

          <br>
          <br>

 
    <%= f.submit "تسجيل",:id=>"signup-submit",:class=>"btn btn-lg btn-primary btn-block" %>

  <% end %>
  </div>
</div>
</div>
</div>
</div>

<style type="text/css">
.fullscreen-bg {
  background: url("/assets/baby1.jpg") repeat scroll 0 0 transparent !important;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
#signinn {
 margin-top:98px;
}
.navbar-default {
    z-index: 150;
    position: relative;
    width: 100%;
    background-color: #FFF;
    padding: 10px 0 10px;
    border-radius: 0;
    border-bottom: 1px solid rgba(0, 0, 0, 0.09);
    -webkit-box-shadow: 0 2px 2px rgba(0,0,0,.1);
    box-shadow: 0 2px 2px rgba(0,0,0,.1);
  }
  .heading-border{
  border: 1px solid rgb(218, 200, 200);
  padding: 30px;
}
.heading-border .panel-heading {
  position: relative;
  height: 50px;
  padding: 0;
  overflow: hidden;
  border-bottom: 1px solid transparent;
}
.panel-title {
  font-weight: 500;
  padding-right: 20px;
  font-size: 1em;
  line-height: 30px;
}

.admin-form {
  line-height: 1.231;
  font-weight: 400;
  font-size: 14px;
  color: #626262;
}

.admin-form .gui-input {
  -webkit-tap-highlight-color: transparent;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
.admin-form label{
  margin: 0;
  font-size: 14px;
  font-weight: 400;
  color: #626262;
  outline: none;
}

.admin-form .field-icon i {
  color: #BBB;
  position: relative;
}
.admin-form .field-label {
  display: block;
  margin-bottom: 7px;
}
.admin-form .gui-input{
  position: relative;
  vertical-align: top;
  border: 1px solid #DDD;
  display: -moz-inline-stack;
  display: inline-block;
  display: inline;
  color: #626262;
  outline: none;
  height: 42px;
  width: 100%;
  zoom: 1;
}
.admin-form .form-control:focus ~ .field-icon i {
  color: #555;
}
.admin-form .prepend-icon {
  top: 0;
  left: 0;
  display: inline-block;
  vertical-align: top;
  position: relative;
  width: 100%;
}
.admin-form .prepend-icon .field-icon {
  top: 0;
  left: 0;
  z-index: 4;
  width: 42px;
  height: 35px;
  color: inherit;
  line-height: 35px;
  position: absolute;
  text-align: center;
  -webkit-transition: all 0.5s ease-out;
  -moz-transition: all 0.5s ease-out;
  -ms-transition: all 0.5s ease-out;
  -o-transition: all 0.5s ease-out;
  transition: all 0.5s ease-out;
  pointer-events: none;
}
.admin-form .append-icon .field-icon i,
.admin-form .prepend-icon .field-icon i {
  position: relative;
  font-size: 14px;
}

.admin-form .prepend-icon > input {
      padding-right: 7px;
}
</style>

<script>
 
$(document).ready(function(){

    var signup = {
    formbox: $('#user'),
    emailbox: $("#signup-email"),
    usernamebox: $("#username"),
    passwordbox: $("#signup-pass"),
    confirmbox: $("#pass_confirm"),
    valid: {"signup-email": false,"username": false,"pass_confirm": false,"signup-pass": false},
    showError: function(id, msg) {
      var error = $('<p>').addClass('error').text(msg);
      error.insertAfter('#'+id);
      $('#'+id).addClass('error-box');
    },
    resetValidation: function(id){
      $('#'+id).siblings('.error').remove();
      $('#'+id).removeClass('error-box');
      this.valid[id] = true;
    },
    resetAllValidation: function() {
      this.formbox.siblings('.error').remove();
      this.formbox.siblings('.error').remove();
      for (myvar in this.valid) {
        this.valid[myvar] = true;
      }
    },
    validateEmail: function() {
      var email = this.emailbox.val();
        id = this.emailbox.attr('id');
        pattern = /^[\w.%+-]+@([\w-]+\.)+[\w]{2,}$/i;

      if (email == ''|| email==null || email == "undefined") {
        this.showError(id, "يجب إدخال البريد الالكتروني");
        this.valid[id] = false;
      } else if (!pattern.test(email)){
        this.showError(id, "يرجى استخدام بريد الكتروني صحيح");
        this.valid[id] = false;
      } else {
        var that = this;
        $.ajax({
          type: 'POST',
          url: '<%=check_email_main_index_path%>',
          data: {email: email},
          //async: false,
          complete: function(jqXHR, textStatus){
            if(jqXHR.status == "203"){
              that.valid[id] = false;
              that.showError(id, "البريد الالكتروني مسجل مسبقا");
            }else if(jqXHR.status == "202"){
              //valid
              

            }
          }
        });
      }
    },
    validateUsername: function() {
      var user = this.usernamebox.val();
        id = this.usernamebox.attr('id');

      if (user == ''|| user==null || user == "undefined") {
        this.showError(id, "يجب ادخال اسم المستخدم");
        this.valid[id] = false;
      } else if (user.length < 3 ){
        this.showError(id, "يجب ان يكون اسم المستخدم اكثر من 3 خانات");
        this.valid[id] = false;
      } else {
        var that = this;
        $.ajax({
          type: 'POST',
          url: '<%=check_username_main_index_path%>',
          data: {username: user},
          //async: false,
          complete: function(jqXHR, textStatus){
            if(jqXHR.status == "203"){
              that.valid[id] = false;
              that.showError(id, "إسم المستخدم موجود");
            }else if(jqXHR.status == "202"){
              //valid
            }
          }
        });
      }
    },
    validatePassword: function() {
      var password = this.passwordbox.val();
        id = this.passwordbox.attr('id');

      if (password == ''|| password==null || password == "undefined") {
        this.showError(id, "يجب ادخال كلمة المرور");
        this.valid[id] = false;
      } else if (password.length < 6 ){
        this.showError(id, "يجب ان تكون كلمة المرور اكثر من 6 خانات");
        this.valid[id] = false;
      }
    },
    validateConfirm: function() {
      var confirm = this.confirmbox.val();
      var password = this.passwordbox.val();
        id = this.confirmbox.attr('id');

      if (confirm == ''|| confirm==null || confirm == "undefined") {
        this.showError(id, "يجب تأكيد كلمة المرور");
        this.valid[id] = false;
      } else if (confirm.length < 6 ){
        this.showError(id, "يجب ان تكون كلمة المرور اكثر من 6 خانات");
        this.valid[id] = false;
      } else if(confirm != password){
        this.showError(id, "لم تتطابق مع كلمة المرور");
        this.valid[id] = false;
      }
    },
    
  };

  $("#signup-submit").click(function(e){
    for (myvar in signup.valid) {
      if (! signup.valid[myvar]) {
        e.preventDefault();
        return false;
      }
    }
    signup.resetAllValidation();
    signup.validateOriginalLanguage();
  });

  $("#signup-email, #signup-pass, #signup-site, #username, #pass_confirm").focus(function(){
    signup.resetValidation($(this).attr('id'));
  });
  $("#signup-email").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validateEmail();
  });
  $("#signup-pass").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validatePassword();
  });
  $("#pass_confirm").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validateConfirm();
  });
  $("#username").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validateUsername();
  });


});
</script>