config/routes.rb
Hadhada::Application.routes.draw do

  root  :to=>'main#index'

    resources :article,:except=>[:show] do
       collection do
         get :new_article
         post :create_article
         get :add_icon
         post :icon
       end
    end

    resources :comment do
      collection do
        post :create_comment
      end
    end

    resources :dashboard do
       collection do
         get :add_user
         post :create_user
       end
    end
get '/login', :to => 'main#sign', via: :get
    resources :main do
       collection do
         get :sign
         post :sign_in
         get :signup
         post :sign_up
         get :sign_out
         post :check_email
         post :check_username
       end
    end

    resources :category do
       collection do
       end
    end

    resources :sound do
       collection do
        get :sounds
       end
    end

    resources :quote do
       collection do
       end
    end

    resources :planer do
      collection do
      end
    end

  match '/planer/download/:filename', :action => 'download', :via => [:get], :controller => 'planer'
  match '/:category/:article/:id', :action => 'show', :via => [:get], :controller => 'article'

  match '*a', :to => 'application#routing', via: :get
  get '/404', :to => 'application#routing', via: :get
  get '/500', :to => 'application#server', via: :get
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate

	layout "admin_layout"
	

	def index
		
	end

	def add_user
		render :layout => 'content_layout'
	end

	def create_user
		params.permit!
		params[:user].each{|k,v| v.downcase! rescue v}
		@user=User.new(params[:user])
		@user.encrypted_password=Digest::MD5.hexdigest(params[:user][:password]+"hadhada")
		if @user.save
			redirect_to dashboard_index_path,:flash => { :success => "تم إنشاء المستخدم" } and return
		else
			redirect_to dashboard_index_path,:flash => { :alert => "لم يتم إنشاء المستخدم" } and return
		end
	end

	

	# def edit_info
	# end

	# def info
	# 	params.permit!	
	# 	if @user.update(params[:user])
	# 		redirect_to dashboard_index_path,:flash => { :success => "Info edited!" } and return
	# 	else
	# 		redirect_to edit_info_dashboard_index_path,:flash => { :alert => "Sorry could not edit info!" } and return
	# 	end
	# end

	# def edit_pass
	# 	params.permit!
	# 	@user.encrypted_password=Digest::MD5.hexdigest(params[:user][:password]+"supportdakwak")
	# 	if @user.update(params[:user])
	# 		redirect_to dashboard_index_path,:flash => { :success => "Info edited!" } and return
	# 	else
	# 		redirect_to edit_info_dashboard_index_path,:flash => { :alert => "Sorry could not edit info!" } and return
	# 	end
	# end

	# def edit_website
	# if params[:website]
	# 	params.permit!
	# 	request=Ticket.create(params[:website])
	# 	request.website_id=@current_website.id
	# 	request.status="pending"
	# 	 if request.save
	# 	 	flash[:success]= "Your request was sent, we'll contact you as soon as possible."
	# 	 	TicketMailer.update_request(request).deliver
	# 	 else
	# 	 	flash[:alert]= "Somthing went wrong. please try again. check our FAQs for more info."
	# 	 end
	# end
	# 	redirect_to dashboard_index_path
	# end

	# def add_types
	# end

	# def types
	# 	params.permit!	
	# 	@cats=Category.all
	# 	@website.chosen_categorys=[]
	# 	@cats.each do |cat|
	# 		if params[cat.id.to_s.to_sym]
	# 			if @website
	# 				@website.chosen_categorys<<cat.value
	# 				@website.save!
	# 			end
	# 		end
	# 	end
	# 	if @user.save!
	# 		redirect_to dashboard_index_path,:flash => { :success => "Categories edited!" } and return
	# 	else
	# 		redirect_to edit_info_dashboard_index_path,:flash => { :alert => "Sorry could not edit Categories!" } and return
	# 	end
	# end

	# def delete_account
	# 	if @user.destroy
	# 	session[:user]=nil
 #  		session[:user_steps]=nil
 #  		redirect_to root_path,:flash => { :alert => "Account was DELETED" }
 #  	    end
	# end

	# def contact_info
	# 	if !@current_website.contact
	# 		@contact=Contact.new
	# 	else
	# 		@contact=@current_website.contact
	# 	end
	# end

	# def contact
	# 	params.permit!
	# 	@contact=Contact.find_or_create_by(:website_id=>@website.id)
	# 	@contact.website_id=@website.id
	# 	if @contact.update(params[:contact])
	# 		flash[:success]="contact info added to website"
	# 		redirect_to dashboard_index_path
	# 	else
	# 		flash[:alert]="Error in contact entering"
	# 		redirect_to contact_info_dashboard_index_path
	# 	end

	# end

	# def edit_icon
	# end

	# def icon
	# 	post = params[:website][:avatar]
	# 	#extension = File.extname(params[:website][:avatar].original_filename)
	# 	f= post.open
	# 	File.write(File.expand_path("public/logos/#{@website.id}.png"),f.read)
	# 	@website.avatar="public/logos/#{@website.id}.png"
	# 	@website.save! rescue redirect_to dashboard_index_path,:flash => { :alert => "failed" } and return
	# 	redirect_to dashboard_index_path,:flash => { :success => "Added Icon" }

	# end

	# def logo_text
	# 	params.permit!
	# 	@website.logo_text=params[:website][:logo_text]
	# 	FileUtils.rm("public/logos/#{@website.id}.png") rescue nil
	# 	@website.avatar=nil
	# 	if @website.save!
	# 		redirect_to dashboard_index_path,:flash => { :success => "Added Icon" }
	# 	end
	# end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/add_user.html.erb
<% @page_title = "SignUp" %>

<div id="signinn">
<div class="container">

<div class=" col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3 ">
<div class="admin-form theme-primary mw1000 center-block" style="padding-bottom: 100px;">

   <div class="panel heading-border panel-primary">
  <%= form_for(:user,:url=>create_user_dashboard_index_path,:html => {:id => "user"}) do |f| %>
            <div class="panel-heading">
                  <h3 class="panel-title" style="font-size:1.5em;">مستخدم جديد</h3>
            </div>

            <label for="username" class="field prepend-icon">
      <%= f.text_field :username, :class=>"form-control",
          :required=>"true",:placeholder=>"إسم المستخدم" ,:id=>"username"%>
          <label for="username" class="field-icon">
              <i class="fa fa-user"></i>
          </label>

          </label>

          <br>
          <br>

  <label for="email" class="field prepend-icon">
    <%= f.text_field :email,:class=>"form-control",:placeholder=>"البريد الالكتروني", :required=>"true",:id=>"signup-email"%> 
    <label for="email" class="field-icon">
              <i class="fa fa-envelope"></i>
          </label>
          </label>

          <br>
          <br>


    <label for="password" class="field prepend-icon">
    <%= f.password_field :password,:id=>"pass",:class=>"form-control" ,:placeholder=>"كلمة المرور", :required=>"true",:id=>"signup-pass"%>
    <label for="password" class="field-icon">
              <i class="fa fa-lock"></i>
          </label>
          </label>

          <br>
          <br>




    <label for="password_confirmation" class="field prepend-icon">
    <%= f.password_field :password_confirmation,:class=>"form-control" ,:placeholder=>"تأكيد كلمة المرور", :required=>"true",:id=>"pass_confirm"%>
    <label for="password_confirmation" class="field-icon">
              <i class="fa fa-check"></i>
          </label>
          </label>

          <br>
          <br>
    <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
 <br>
          <br>
 
    <%= f.submit "تسجيل",:id=>"signup-submit",:class=>"btn btn-lg btn-primary btn-block" %>

  <% end %>
  </div>
</div>
</div>
</div>
</div>

<style type="text/css">
.fullscreen-bg {
  background: url("/assets/baby1.jpg") repeat scroll 0 0 transparent !important;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
#signinn {
 margin-top:88px;
}
.heading-border{
  border: 1px solid rgb(218, 200, 200);
  padding: 30px;
}
.heading-border .panel-heading {
  position: relative;
  height: 50px;
  padding: 0;
  overflow: hidden;
  border-bottom: 1px solid transparent;
}
.panel-title {
  font-weight: 500;
  padding-right: 20px;
  font-size: 1em;
  line-height: 30px;
}

.admin-form {
  line-height: 1.231;
  font-weight: 400;
  font-size: 14px;
  color: #626262;
}

.admin-form .gui-input {
  -webkit-tap-highlight-color: transparent;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
.admin-form label{
  margin: 0;
  font-size: 14px;
  font-weight: 400;
  color: #626262;
  outline: none;
}

.admin-form .field-icon i {
  color: #BBB;
  position: relative;
}
.admin-form .field-label {
  display: block;
  margin-bottom: 7px;
}
.admin-form .gui-input{
  position: relative;
  vertical-align: top;
  border: 1px solid #DDD;
  display: -moz-inline-stack;
  display: inline-block;
  display: inline;
  color: #626262;
  outline: none;
  height: 42px;
  width: 100%;
  zoom: 1;
}
.admin-form .form-control:focus ~ .field-icon i {
  color: #555;
}
.admin-form .prepend-icon {
  top: 0;
  left: 0;
  display: inline-block;
  vertical-align: top;
  position: relative;
  width: 100%;
}
.admin-form .prepend-icon .field-icon {
  top: 0;
  left: 0;
  z-index: 4;
  width: 42px;
  height: 35px;
  color: inherit;
  line-height: 35px;
  position: absolute;
  text-align: center;
  -webkit-transition: all 0.5s ease-out;
  -moz-transition: all 0.5s ease-out;
  -ms-transition: all 0.5s ease-out;
  -o-transition: all 0.5s ease-out;
  transition: all 0.5s ease-out;
  pointer-events: none;
}
.admin-form .append-icon .field-icon i,
.admin-form .prepend-icon .field-icon i {
  position: relative;
  font-size: 14px;
}

.admin-form .prepend-icon > input {
      padding-right: 7px;
}
</style>

<script>
 
$(document).ready(function(){

    var signup = {
    formbox: $('#user'),
    emailbox: $("#signup-email"),
    usernamebox: $("#username"),
    passwordbox: $("#signup-pass"),
    confirmbox: $("#pass_confirm"),
    valid: {"signup-email": false,"username": false,"pass_confirm": false,"signup-pass": false},
    showError: function(id, msg) {
      var error = $('<p>').addClass('error').text(msg);
      error.insertAfter('#'+id);
      $('#'+id).addClass('error-box');
    },
    resetValidation: function(id){
      $('#'+id).siblings('.error').remove();
      $('#'+id).removeClass('error-box');
      this.valid[id] = true;
    },
    resetAllValidation: function() {
      this.formbox.siblings('.error').remove();
      this.formbox.siblings('.error').remove();
      for (myvar in this.valid) {
        this.valid[myvar] = true;
      }
    },
    validateEmail: function() {
      var email = this.emailbox.val();
        id = this.emailbox.attr('id');
        pattern = /^[\w.%+-]+@([\w-]+\.)+[\w]{2,}$/i;

      if (email == ''|| email==null || email == "undefined") {
        this.showError(id, "يجب إدخال البريد الالكتروني");
        this.valid[id] = false;
      } else if (!pattern.test(email)){
        this.showError(id, "يرجى استخدام بريد الكتروني صحيح");
        this.valid[id] = false;
      } else {
        var that = this;
        $.ajax({
          type: 'POST',
          url: '<%=check_email_main_index_path%>',
          data: {email: email},
          //async: false,
          complete: function(jqXHR, textStatus){
            if(jqXHR.status == "203"){
              that.valid[id] = false;
              that.showError(id, "البريد الالكتروني مسجل مسبقا");
            }else if(jqXHR.status == "202"){
              //valid
              

            }
          }
        });
      }
    },
    validateUsername: function() {
      var user = this.usernamebox.val();
        id = this.usernamebox.attr('id');

      if (user == ''|| user==null || user == "undefined") {
        this.showError(id, "يجب ادخال اسم المستخدم");
        this.valid[id] = false;
      } else if (user.length < 3 ){
        this.showError(id, "يجب ان يكون اسم المستخدم اكثر من 3 خانات");
        this.valid[id] = false;
      } else {
        var that = this;
        $.ajax({
          type: 'POST',
          url: '<%=check_username_main_index_path%>',
          data: {username: user},
          //async: false,
          complete: function(jqXHR, textStatus){
            if(jqXHR.status == "203"){
              that.valid[id] = false;
              that.showError(id, "إسم المستخدم موجود");
            }else if(jqXHR.status == "202"){
              //valid
            }
          }
        });
      }
    },
    validatePassword: function() {
      var password = this.passwordbox.val();
        id = this.passwordbox.attr('id');

      if (password == ''|| password==null || password == "undefined") {
        this.showError(id, "يجب ادخال كلمة المرور");
        this.valid[id] = false;
      } else if (password.length < 6 ){
        this.showError(id, "يجب ان تكون كلمة المرور اكثر من 6 خانات");
        this.valid[id] = false;
      }
    },
    validateConfirm: function() {
      var confirm = this.confirmbox.val();
      var password = this.passwordbox.val();
        id = this.confirmbox.attr('id');

      if (confirm == ''|| confirm==null || confirm == "undefined") {
        this.showError(id, "يجب تأكيد كلمة المرور");
        this.valid[id] = false;
      } else if (confirm.length < 6 ){
        this.showError(id, "يجب ان تكون كلمة المرور اكثر من 6 خانات");
        this.valid[id] = false;
      } else if(confirm != password){
        this.showError(id, "لم تتطابق مع كلمة المرور");
        this.valid[id] = false;
      }
    },
    
  };

  $("#signup-submit").click(function(e){
    for (myvar in signup.valid) {
      if (! signup.valid[myvar]) {
        e.preventDefault();
        return false;
      }
    }
    signup.resetAllValidation();
    signup.validateOriginalLanguage();
  });

  $("#signup-email, #signup-pass, #signup-site, #username, #pass_confirm").focus(function(){
    signup.resetValidation($(this).attr('id'));
  });
  $("#signup-email").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validateEmail();
  });
  $("#signup-pass").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validatePassword();
  });
  $("#pass_confirm").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validateConfirm();
  });
  $("#username").blur(function(){
    signup.resetValidation($(this).attr('id'));
    signup.validateUsername();
  });

  $('#username').val("");
  $('#signup-email').val("");


});
</script>

app/views/dashboard/index.html.erb
<div class="row">
    <div class="col-md-8 col-sm-6">
    	<div class="col-md-4 col-sm-3">
<%= link_to ' مقال جديد ',new_article_article_index_path,:class=>"btn btn-compose fa fa-plus"  ,:data=>{:toggle=>"tooltip", :title=>"مقال جديد"}%>
</div>
<%if can? :create, Sound %> 
<div class="col-md-4 col-sm-3">
<%= link_to ' مقطع جديد ',new_sound_path,:class=>"btn btn-compose  fa fa-plus"  ,:data=>{:toggle=>"tooltip", :title=>"مقطع جديد"}%>
</div>
<%end%>
<%if can? :create, :quote %> 
<div class="col-md-4 col-sm-3">
<%= link_to ' اقتباس جديد ',new_quote_path,:class=>"btn btn-compose  fa fa-plus"  ,:data=>{:toggle=>"tooltip", :title=>"اقتباس جديد"}%>
</div>
<%end%>
</div>
</div>