config/routes.rb
Hadhada::Application.routes.draw do

  root  :to=>'main#index'

    resources :article,:except=>[:show] do
       collection do
         get :new_article
         post :create_article
         get :add_icon
         post :icon
       end
    end

    resources :comment do
      collection do
        post :create_comment
      end
    end

    resources :dashboard do
       collection do
         get :add_user
         post :create_user
       end
    end
get '/login', :to => 'main#sign', via: :get
    resources :main do
       collection do
         get :sign
         post :sign_in
         get :signup
         post :sign_up
         get :sign_out
         post :check_email
         post :check_username
       end
    end

    resources :category do
       collection do
       end
    end

    resources :sound do
       collection do
        get :sounds
       end
    end

    resources :quote do
       collection do
       end
    end

    resources :planer do
      collection do
      end
    end

  match '/planer/download/:filename', :action => 'download', :via => [:get], :controller => 'planer'
  match '/:category/:article/:id', :action => 'show', :via => [:get], :controller => 'article'

  match '*a', :to => 'application#routing', via: :get
  get '/404', :to => 'application#routing', via: :get
  get '/500', :to => 'application#server', via: :get
  

end

app/views/shared/_comment_new.html.erb
<%= form_for(:comment, :url => create_comment_comment_index_path, :remote => true,:html => {:id => "comment"}) do |f| %>
  <input type="hidden" value="<%=params[:id]%>" name="article[id]">
  <div class="field">
    <%= f.text_field :commentor,:class=>"form-control", :required=>"true", :placeholder=>"الإسم" %>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :content,:class=>"form-control", :required=>"true", :placeholder=>"التعليق" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "إضافة",:id=>"submit",:class=>"btn btn-lg btn-primary "%>
  </div>
<% end %>

<script type="text/javascript">
$('#submit').click(function (e) {

        // prevent the default click action
        e.preventDefault();


        var commentor=$('#comment_commentor').val();
        id = $('#comment_commentor').attr('id');

        var content=$('#comment_content').val();
        id2 = $('#comment_content').attr('id');

        if(commentor=="" || commentor==null || commentor==undefined || commentor==" "){
          var error = $('<span class="co">').addClass('error').text('يجب ادخال الإسم');
          $('.co').remove();
          error.insertAfter($('#'+id).parent());
          return false;
        }
        if(content=="" || content==null || commentor==undefined || commentor==" "){
          var error = $('<span class="co2">').addClass('error').text('يجب ادخال التعليق');
          $('.co2').remove();
          error.insertAfter($('#'+id2).parent());
          return false;
        }
        // make an ajax call
        $.ajax({
          
            // make a post request to the server
            type: "POST",
            // get the url from the href attribute of our link
            url: '<%=create_comment_comment_index_path%>',
           
            data: {
              comment: {
                 content: content,
                commentor: commentor,
              },
              article: {
                id:"<%= params[:id] %>"
              }
            },
            // upon success 
            success: function(data, textStatus,jqXHR){
            if(jqXHR.status == "203"){
              //jqXHR.text;
            }else if(jqXHR.status == "202"){
              //valid
              $('#comments').prepend(data);
              $('#comment_commentor').val("");
              $('#comment_content').val("");

            }
          }
        });
    });
$("#comment_commentor").focus(function(){
    $('.co').remove();
  });
$("#comment_content").focus(function(){
    $('.co2').remove();
  });
</script>

app/views/shared/_dashboard.html.erb
<aside>
          <div id="sidebar" class="nav-collapse" tabindex="5000" style="overflow: hidden; outline: none; margin-left: 0px;">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion" style="display: block;">
                <p class="centered person">
<!--   <img src="assets/img/ui-sam.jpg" class="img-circle" width="80"></a>-->
                <i class="fa fa-user"></i>
                </p>
                <h5 class="centered"><%= @user.username%> | <%= @user.role%></h5>
                  <li>
                      <a <%= "class=active" if controller_name=="dashboard" %> href="<%= dashboard_index_path %>">
                          <i class="fa fa-dashboard"></i>
                          <span>لوحة التحكم</span>
                      </a>
                  </li>

                  <li>
                      <a <%= "class=active" if controller_name=="article" %> href="<%= article_index_path %>">
                          <i class="fa fa-th"></i>
                          <span>المقالات</span>
                      </a>
                  </li>
                  <%if can? :manage, Sound %>
                  <li>
                      <a <%= "class=active" if controller_name=="sound" %> href="<%=sounds_sound_index_path%>"> 
                          <i class="fa fa-twitter"></i>
                          <span>هدهدات</span>
                      </a>
                  </li>
                  <%end%>
                  <li>
                      <a <%= "class=active" if controller_name=="" %> href="/set">
                          <i class="fa fa-cogs"></i>
                          <span>الإعدادات</span>
                      </a>
                  </li>
                  <%if can? :create, User %>
                  <li>
                    <a  <%= "class=active" if action_name=="add_user" %> href="<%= add_user_dashboard_index_path %>"> 
                      <i class="fa fa-user-plus"></i>
                      <span>مستخدم جديد</span>
                    </a>
                  </li>
                  <%end%>
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>

app/views/shared/_flash.html.erb
<script>

<% if flash[:alert] %>
toastr.error('<%= flash[:alert].capitalize %>');
<% elsif flash[:info] %>
toastr.info('<%= flash[:info].capitalize %>');
<% elsif flash[:success] %>
toastr.success('<%= flash[:success].capitalize %>');
<% end %>

</script>

app/views/shared/_head.html.erb
<!-- HOME -->
  <section class="home bg-two" id="home">
    <div class="bg-overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center">
          <div class="full-screen">
            <div class="home-wrapper home-wrapper-alt">
              <img alt="هدهدة"  src="/assets/logo2.png" width="280"></a>
              <h1 class="animated fadeInDown wow animated" data-wow-delay=".1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInDown;">ترانيم الطفولة الأولى</h1>
              <!-- <h4 class="animated fadeInDown wow animated" data-wow-delay=".4s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInDown;">كل ما يهم الأم لتعرفه عن طفلها</h4> -->
            </div>
          </div>  
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 text-center" id="cats" style="visibility: hidden; animation-delay: 0.6s;">
          <div >
              <%Category.all.each do |cat|%>
              <%if cat.parent_id==nil%>
                  <div class="col-md-3 col-sm-6">
                      <div class="panel" style="background-color:<%=cat.color%>;">
                          <div class="panel-body text-center" onclick="location.href='<%=category_index_path(:id=>cat.id)%>';" style="cursor:pointer;">
                              <p class="text-uppercase mar-btm text-sm"><%=cat.name%></p>
                                <img src="/assets/<%=cat.id%>a.png">
                                <br>
                                <a href="<%=category_index_path(:id=>cat.id)%>" class="btn btn-md btn-secondary">المزيد</a>
                          </div>
                      </div>
                  </div>
                  <%end%>
              <%end%>
          </div>
        </div>    
      </div>
    </div>
  </section>
  <!-- END HOME -->

app/views/shared/_home_menu.html.erb
<div class="navbar navbar-custom sticky navbar-abs" role="navigation" id="stick">
    <div class="container">
      <!-- Navbar-header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
             <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
        </button>
        <!-- LOGO -->
        <a class="navbar-brand logo" href="/">
        <img alt="هدهدة"  src="/assets/logo1.png" width="170"></a>

        </a>
      </div>
      <!-- end navbar-header -->

      <!-- menu -->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
          <li><a href="/">الرئيسية</a></li>
          <li <%= "class=active" if controller_name=="category" %>><a class="page-scroll" href="#features-flat">الأبواب</a>
        <% categorys=[]
        sub=[]
        Category.all.each do |cat|
      if cat.parent_id==nil
      categorys<<cat.name
      else
      sub<<cat.name
        end
        end %>
        <ul id="drop">
          <li><a href="<%=category_index_path(:id=>1)%>"><%=categorys[3]%></a></li>
          <li><a href="<%=category_index_path(:id=>2)%>"><%=categorys[2]%></a>
            <ul id="lvl2">
          <li><a href="<%=category_index_path(:id=>5)%>"><%=sub[3]%></a></li>
          <li><a href="<%=category_index_path(:id=>6)%>"><%=sub[2]%></a></li>
          <li><a href="<%=category_index_path(:id=>7)%>"><%=sub[1]%></a></li>
          <li><a href="<%=category_index_path(:id=>8)%>"><%=sub[0]%></a></li>
            </ul>
          </li>
          <li><a href="<%=category_index_path(:id=>3)%>"><%=categorys[1]%></a></li>
          <li><a href="<%=category_index_path(:id=>4)%>"><%=categorys[0]%></a></li>
        </ul>
      </li> 
      <li <%= "class=active" if controller_name=="sound" %>><a href="<%= sound_index_path%>">هدهدات</a></li>
      <li <%= "class=active" if controller_name=="planer" %>><a href="<%= planer_index_path%>">الخطة</a></li>
      <% if @user %>
      <li <%= "class=active" if controller_name=="dashboard" %>><a href="<%= dashboard_index_path%>">لوحة التحكم</a></li>
      <li><a href="<%= sign_out_main_index_path %>">تسجيل الخروج <i class="fa fa-sign-out" style="padding-left:4px;"></i></a></li>
      <% else %>
      <!-- <li <%= "class=active" if action_name=="sign" %>><a
        href="<%= sign_main_index_path %>">تسجيل الدخول <i class="fa fa-sign-in" style="padding-left:4px;"></i></a></li> -->
      <% end %>
        </ul>
      </div>
      <!--/Menu -->
    </div>
    <!-- end container -->
  </div>
  <div class="clearfix"></div>

<script>
// from https://signalvnoise.com/posts/2407-device-scale-user-interface-elements-in-ios-mobile-safari
function getDeviceScale() {
    var deviceWidth, landscape = Math.abs(window.orientation) == 90;
    if (landscape) {
      // iPhone OS < 3.2 reports a screen height of 396px
      deviceWidth = Math.max(480, screen.height);
    } else {
      deviceWidth = screen.width;
    }
    return window.innerWidth / deviceWidth;
}

// mobile only - keep the position:fixed header at constant size when page is zoomed
if (navigator.userAgent.match(/Mobi/)) {
    $(window).on('load scroll', function() {
        var ds = getDeviceScale();
        $('.device-fixed-height').css('transform','scale(1,' + ds + ')')
            .css('transform-origin', '0 0');
        $('.device-fixed-width').css('transform', 'scale(' + ds + ',1)')
            .css('transform-origin', '0 0');
        })
}
</script>
<script>
  $(document).ready(function(){
    $("#stick").sticky({topSpacing:0});
  });
  </script>