config/routes.rb
Hadhada::Application.routes.draw do

  root  :to=>'main#index'

    resources :article,:except=>[:show] do
       collection do
         get :new_article
         post :create_article
         get :add_icon
         post :icon
       end
    end

    resources :comment do
      collection do
        post :create_comment
      end
    end

    resources :dashboard do
       collection do
         get :add_user
         post :create_user
       end
    end
get '/login', :to => 'main#sign', via: :get
    resources :main do
       collection do
         get :sign
         post :sign_in
         get :signup
         post :sign_up
         get :sign_out
         post :check_email
         post :check_username
       end
    end

    resources :category do
       collection do
       end
    end

    resources :sound do
       collection do
        get :sounds
       end
    end

    resources :quote do
       collection do
       end
    end

    resources :planer do
      collection do
      end
    end

  match '/planer/download/:filename', :action => 'download', :via => [:get], :controller => 'planer'
  match '/:category/:article/:id', :action => 'show', :via => [:get], :controller => 'article'

  match '*a', :to => 'application#routing', via: :get
  get '/404', :to => 'application#routing', via: :get
  get '/500', :to => 'application#server', via: :get
  

end

app/models/article.rb
class Article < ActiveRecord::Base
	default_scope { order(created_at: :desc) }
	belongs_to :category
	has_many :comments, :dependent => :destroy
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	load_and_authorize_resource

	layout "admin_layout"

	before_filter :authenticate, except: [:show]

	def index
		 @articles=Article.all
	end

	def edit
		 @article = Article.find(params[:id])
	end

	def show
		@article=Article.find(params[:id])
		render :layout => 'content_layout'
	end

	def destroy
    	article = Article.find(params[:id])
    	article.destroy
    	File.delete(File.expand_path("public/images/#{article.id}.png")) rescue nil
    	flash[:alert]= "تم حذف المقال"
    	redirect_to article_index_path
  	end

	def new_article
		@article=Article.new
	end

	def create_article
		if params[:article]
			params.permit!
			article=Article.create(params[:article])
			keyword=params[:article][:title]
			keyword=keyword.gsub("?","")
			keyword=keyword.gsub(".","")
			keyword=keyword.gsub(",","")
			keyword=keyword.gsub("/","")
			article.title=keyword.downcase
			article.color=article.category.color
			article.save
		end

		flash[:success]= "تم إنشاء المقال"
		redirect_to add_icon_article_index_path(:id=>article.id)
	end


	def update
		article=Article.find(params[:id])
		article.category_id=params[:article][:category_id]
		article.content=params[:article][:content]
		article.color=article.category.color
		keyword=params[:article][:title]
		keyword=keyword.gsub("?","")
		keyword=keyword.gsub(".","")
		keyword=keyword.gsub(",","")
		keyword=keyword.gsub("/","")
		article.title=keyword.downcase
		article.save

		flash[:success]= "تم تعديل المقال"
		redirect_to article_index_path
	end

	def add_icon
		@article=Article.where(:id=>params[:id])
	end

	def icon
	    article=Article.find(params[:article][:id])
		tmp =params[:article][:icon].tempfile
    	file = File.join("public/images/","#{article.id}.png")
    	FileUtils.cp tmp.path, file
    	FileUtils.chmod 775, file
		# if post.content_type=="image/jpeg"
		# File.write(File.expand_path("public/images/#{article.id}.jpg"),f.read)
		# article.icon="public/images/#{article.id}.jpg"
		# else
		#File.write(File.expand_path("public/images/#{article.id}.png"),f.read)
		article.icon="public/images/#{article.id}.png"
		# end
		article.save! rescue redirect_to dashboard_index_path,:flash => { :alert => "لم يتم اضافة الصورة" } and return
		redirect_to dashboard_index_path,:flash => { :success => "تمت اضافة الصورة" }
	end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/_form.html.erb
<%= form_for(@article,:url=>url) do |f|%>

   
    <%= f.text_field :title,:class=>"form-control", :required=>"true", :placeholder=>"عنوان المقال" %>
  <br />

  <% categorys=[]
  Category.all.each do |cat|
    if cat.id!=2
  categorys<<[cat.name,cat.id]
    end
      end %>

 <%= f.select :category_id,
   categorys, {:include_blank=>"اختر الباب"}, { :class=>"form-control", :required => true } %>
  <br />

  <div class="col-lg-12">
   <%= text_area_tag :text_marked,nil,:data=>{:provide => "markdown-editable",:iconlibrary => "fa"},:style=>"height:400px;",:class=>"form-control",:placeholder=>"النص"%> 
   </div>


<div class="col-lg-12" style="margin-top: 30px;">
   <%= f.text_area :content,:style=>"height:300px;background-color:#eee;",:class=>"form-control", :required=>"true",:placeholder=>"HTML tags" %>
   </div>
  

  <div class="col-lg-12 text-center">
    <div style="margin-top:30px;margin-bottom:30px;">
    <%= f.submit 'تعديل المقال', :class => "btn btn-success" %>
    <%= link_to "عودة",article_index_path,:class=>"btn btn-default", :data=>{:placement=>"bottom",:toggle=>"tooltip", :title=>"عودة"} %>
</div>
  </div>
<% end %>
</div>

<style>


#article_type option {font-size: 1.2em;}

.btn-toolbar{float: right;}

</style>

<script type="text/javascript">
$(document).ready(function(){

  $("#text_marked").markdown({
      onShow: function(e){
  $("#text_marked").text( toMarkdown($("#article_content").val(),{gfm: true} ));

},
  savable:false, fullscreen: false,

  onSave: function(e) {
    $('#article_content').text( e.parseContent() );
  },
   onChange: function(e){
     $('#article_content').text( e.parseContent() );
  }

});
});
</script>

app/views/article/add_icon.html.erb
<div class="Sign_Form col-lg-4 col-lg-offset-4">
	<h2 class="form-signin-heading text-center" style="color:#B0ABAB;">إضافة صورة</h2>
  
 <%= form_for(:article,:class=>"form-signin", :url => {:controller => 'article', :action => 'icon'},:html => {:id => "article_icon"} ,:multipart => true) do |f| %>

  <div class="row">
      <div class=" form-group text-center">                            
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <input type="hidden" value="" name="article[icon]">
      <input type="hidden" value="<%=params[:id]%>" name="article[id]">
      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px; line-height: 150px;"></div><br>
      <div>
      <span class="btn btn-icon btn-icon-left btn-primary btn-file">
        <i class="fa fa-cloud-upload"></i>
        <span class="fileinput-new">إختر صورة</span>
        <%= f.file_field 'icon' , :id=>"fileinput_thumb" ,:required=>true %>
      </span>
      <button class="btn btn-icon btn-danger fileinput-exists" data-dismiss="fileinput">
      <i class="fa fa-times"></i>
            Remove
      </button>
               
      </div>
      </div><!-- /fileinput -->
      </div>
  </div>

    <%= f.submit 'إضافة',:class=>"btn btn-lg btn-primary btn-block" %>

 <%end%>
</div>

<style type="text/css">
/*-----fileinput for icon-------*/
.fileinput {
  display: inline-block;
  margin-bottom: 9px;
}

  .fileinput .thumbnail {
  display: inline-block;
  margin-bottom: 5px;
  overflow: hidden;
  text-align: center;
  vertical-align: middle;
  border-color: #e7edf2;}

  .thumbnail {
  display: block;
  padding: 4px;
  margin-bottom: 20px;
  line-height: 1.42857;
  background-color: #fff;
  border: 1px solid #e7edf2;
  border-radius: 4px;
  transition: all .2s ease-in-out;
}

.btn-file>input {
  position: absolute;
  top: 0;
  right: 0;
  margin: 0;
  font-size: 23px;
  cursor: pointer;
  opacity: 0;
  direction: ltr;
  }

  .fileinput .btn {
  vertical-align: middle;}
  .btn-file {
  position: relative;
  overflow: hidden;
  vertical-align: middle;}

  .fileinput-new .fileinput-exists {
  display: none;}

  .fileinput .btn {
  vertical-align: middle;}



/*-------end of fileinput-----------*/



</style>

app/views/article/edit.html.erb
<div class="text-center">
  <h1 style="padding-bottom:23px;">تعديل المقال</h1>
</div>

<div class="Sign_Form col-lg-8 col-lg-offset-2 ">
	<%= render 'form', :url => article_path(:id=>@article) %>
</div>

app/views/article/index.html.erb
<div class="row" style="margin-top:35px;">
    <% @articles.each do |article| %>
         <div class="col-sm-6 col-lg-4 pull-right">
            <div class="panel" style="border: 1px solid #ddd;">
                  <div class="panel-heading" style="background-color:#202d3b;
                   color: #fff;">
                    <h4 class="panel-title">
                     <%if article.title.length>40%>
                        <%=article.title.first(37) %>...
                        <%else%>
                        <%= article.title %>
                        <%end%>
                    </h4>
                  </div>
                <div class="panel-footer">

                    <a class="btn btn-link btn-xs" href="<%=edit_article_path(:id=>article.id)%>" data-placement="bottom" data-toggle="tooltip" data-original-title="تعديل"><i class="fa fa-pencil"></i>
                    </a>
                    <%= link_to " ",article_path(:id=>article.id),:method=>"delete" ,:class=>"btn btn-link btn-xs fa fa-trash", :data=>{:placement=>"bottom",:confirm=>"هل أنت متأكد؟", :toggle=>"tooltip", :title=>"حذف"} %>
                    <a  class="text-capitalize pull-right btn btn-link btn-xs">
                    <%= article.category.name%></a> 
                    
                </div>
            </div>
        </a>
        </div>
    <%end%>
</div>

app/views/article/new_article.html.erb
<div class="text-center">
  <h1 style="padding-bottom:23px;">مقال جديد</h1>
</div>

<div class="Sign_Form col-lg-8 col-lg-offset-2 ">

<%= form_for(@article,:url=>create_article_article_index_path) do |f|%>

   
    <%= f.text_field :title,:class=>"form-control", :required=>"true", :placeholder=>"عنوان المقال" %>
  <br />

  <% categorys=[]
     # sub=[]
  Category.all.each do |cat|
     if cat.id!=2
  categorys<<[cat.name,cat.id]
  #   else
  # sub<<[cat.name,cat.id]
     end
      end %>

 <%= f.select :category_id,
   categorys, {:include_blank=>"اختر الباب"}, { :class=>"form-control", :required => true } %>
  <br />

  <div class="col-lg-12">
   <%= text_area_tag :text_marked,nil,:data=>{:provide => "markdown-editable",:iconlibrary => "fa"},:style=>"height:400px;",:class=>"form-control",:placeholder=>"النص"%> 
   </div>


<div class="col-lg-12" style="margin-top: 30px;">
   <%= f.text_area :content,:style=>"height:300px;background-color:#eee;",:class=>"form-control", :required=>"true",:placeholder=>"HTML tags"%>
   </div>
  

  <div class="col-lg-12 text-center">
    <div style="margin-top:30px;margin-bottom:30px;">
    <%= f.submit 'إنشاء المقال', :class => "btn btn-success" %>
    <%= link_to "عودة",dashboard_index_path,:class=>"btn btn-default", :data=>{:placement=>"bottom",:toggle=>"tooltip", :title=>"عودة"} %>
</div>
  </div>
<% end %>
</div>

<style type="text/css">
#article_type option {font-size: 1.2em;}

.btn-toolbar{float: right;}

</style>

<script type="text/javascript">
$(document).ready(function(){

  $("#text_marked").markdown({
  savable:false, fullscreen: false,

  onSave: function(e) {
    $('#article_content').text( e.parseContent() );
  },
   onChange: function(e){
     $('#article_content').text( e.parseContent() );
  }

});
});
</script>

app/views/article/show.html.erb
<div id="PageContainer" class="is-moved-by-drawer">
      <main role="main" id="Main">
         <div class="page-block sub-page-block">
          <div class="page-width">
            <div class="grid-container">

 <div id="content" class="article marketing-markdown grid-item grid--last grid-6">

                  <h1><%=@article.title%></h1>
    <div class="post-details pull-right">
    <div class="pull-right"><i class="fa fa-calendar"></i> <%=@article.created_at.strftime("%Y/%m/%d")%>&nbsp;&nbsp;&nbsp;
      <i class="fa fa-comment-o"></i> 
        <span class="font-lato"><%= @article.comments.count%></span>
    </div>
    </div>
    <br>
    <div class="img-wrapper">
    <img class="scale" src="/images/<%=@article.id%>.png" alt="<%=@article.title%>">
    </div>
  <%=@article.content.html_safe%>
  
  <br><br><br>
  <h4>اترك تعليقاً</h4>
  <hr>
  <%= render 'shared/comment_new'%>
<br><br>

<div id="comments">
</div>

<%@article.comments.each do |comm|%>
  <div class="row" id="<%=comm.id%>">
      <div class="col-md-10 col-sm-10">
      <div class="panel panel-default arrow right">
        <div class="panel-body">
          <header class="text-right">
            <div class="comment-user"><i class="fa fa-user"></i> <%=comm.commentor%></div>
              <span class="comment-date"><i class="fa fa-clock-o"></i> <%= l(comm.created_at, format: '%Y/%m/%d') %></span>
          </header>
        <div class="comment-post">
        <p><%=comm.content%></p>
        </div>
        <%if can? :destroy, Comment %> 
        <%= link_to " ",comment_path(:id=>comm.id),remote: true,:method=>"delete" ,:class=>"btn btn-link btn-xs fa fa-trash del-comment",:data=>{:placement=>"bottom",:confirm=>"هل أنت متأكد؟", :toggle=>"tooltip", :title=>"حذف"} %>
        <%end%>
        </div>
      </div>
      </div>
       <div class="col-md-2 col-sm-2 hidden-xs">
        <figure class="thumbnail">
          <img class="img-responsive" src="/assets/avatar2.jpg">
        </figure>
      </div>
  </div>
<%end%>
 </div>


<!-- <div class="col-md-3 col-sm-6 pull-right">
  <div class="profile widget">
    <div class="widget-header bg-success"></div>
        <div class="widget-body text-center">
          <img alt="Profile Picture" class="widget-img img-circle img-border" src="/assets/av3.png">
          <h4 class="mar-no">محمد البداوي</h4>
          <p class="text-muted mar-btm">كاتب ومحلل سياسي.</p>
        </div>
  </div>
</div> -->


    <div id="sidemenu" class="sticky-menu hide--mobile pull-right" data-swiftype-index="false">
      <aside class="sidemenu-column" role="navigation" aria-label="manual Menu">
        <span class="sidemenu-nav-header text-capitalize"><%= @article.category.name%></span>
        <ul class="in-page-menu sidemenu-menu">
         <% @article.category.articles.first(10).each do |arts| %>
           <li class="sidemenu-menu__item">
           <a href="/<%= arts.category.name.split(' ').join('-')%>/<%= arts.title.split(' ').join('-')%>/<%=arts.id%>"><%=arts.title%></a>
           </li>
<% end %>
        </ul>
  </aside>
</div>

<div  class="pull-right col-md-3 col-sm-6 pictures">
      <img src="/assets/back2.png" style="margin-top:5em;margin-right:1em;">
      <img src="/assets/back3.png" style="margin-top:6em;">
</div>

</div>
          </div>
        </div>
      </main>
    </div>
<div class="push"></div>
 <!-- Footer -->
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-left">
                <span class="copyright text-muted">Copyright &copy; 
                    <a href="#" target="_blank">
                    <b>Hadhada</b>
                    </a> 2016</span>
                </div>
                <div class="col-md-6 text-right">
                  <div class="social-area pull-right">                
                    <a class="btn btn-social btn-facebook btn-simple" href="#" target="_blank">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                    <a class="btn btn-social btn-twitter btn-simple" href="#" target="_blank">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-social btn-instagram btn-simple" href="#" target="_blank">
                        <i class="fa fa-instagram"></i>
                    </a>
                </div>
                </div>
            </div>
        </div>
    </footer>


<script type="text/javascript">

$(document).ready(function(){

$(function () {
    var url = window.location.href; 
    var activePage = url.substring(url.lastIndexOf('/') + 1);
    var flag=false;
        $('.in-page-menu .sidemenu-menu__item a').each(function () {
            var linkPage = this.href.substring(this.href.lastIndexOf('/') + 1); 
 
            if (activePage == linkPage) { 
              $(this).addClass('active');
              flag=true;
                
            }

        });

        if(flag==false)
        {
          $('.sidemenu-menu__item a').first().addClass('active');
        }
});


$(".del-comment").bind('ajax:success', function(event, xhr, status) {
  if(status == "success"){
    $('#'+xhr).remove();
  }
   });
});
</script>

<style type="text/css">
@media (max-width: 468px){
.sidemenu-column {
    margin-top: 29px;
    padding-bottom: 15px;
    margin-left: 35px;
}
.profile {
    margin-right: 70px;
    margin-top: 40px;
}
.pictures{
  display: none;
}
}
@media (min-width: 768px){
.panel.arrow.right:before {
    right: -16px;
    top: 30px;
    border-left-color: inherit;
    border-width: 16px;
}
.arrow:after, .arrow:before {
    content: "";
    position: absolute;
    width: 0;
    height: 0;
    border-style: solid;
    border-color: transparent;
}
.panel.arrow.right:after {
    right: -14px;
    top: 31px;
    border-left-color: #FFFFFF;
    border-width: 15px;
}
.profile {
    margin-top: 60px;
    margin-right: -30px;
    margin-left: 46px;
}
}
.profile {
    margin-top: 40px;
}
.profile {
    background-color: #fff;
    box-shadow: 0 2px 0 rgba(0,0,0,0.075);
    border: 1px solid #DAD7D7;
    margin-bottom: 15px;  

}
.profile .profile-heading, .profile>:first-child {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.bg-success, .bg-success a {
    color: #fff;
}
.bg-success {
    background-color: #5B7E88;
}
.widget-header {
    padding: 15px 15px 50px 15px;
    min-height: 65px;
    position: relative;
    overflow: hidden;
}
.profile .profile-footer, .profile>:last-child {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.widget-body {
    padding: 50px 15px 15px;
    position: relative;
}
.widget-img {
    position: absolute;
    width: 64px;
    height: 64px;
    left: 50%;
    margin-left: -32px;
    top: -32px;
}

.img-border {
    box-shadow: 0 0 0 4px rgba(0,0,0,0.1);
}
.img-circle {
    border-radius: 50%;
}
.text-muted, a.text-muted:hover, a.text-muted:focus {
    color: #acacac;
}
.thumbnail {
    display: block;
    padding: 4px;
    margin-bottom: 20px;
    line-height: 1.42857143;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 4px;
    -webkit-transition: border .2s ease-in-out;
    -o-transition: border .2s ease-in-out;
    transition: border .2s ease-in-out;
}
figure {
    margin: 0;
}
div.row>div img.img-responsive {
    width: 100%;
}

img.img-responsive {
    display: inline-block;
}
.text-right {
    text-align: right; !important;
}
.comment-post {
    margin-top: 10px;
}
/*---end of comments*/
#PageContainer {
    overflow: hidden;
    width: 100%;
}
#PageContainer:before {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    visibility: hidden;
    opacity: 0;
    background-color: rgba(0, 0, 0, 0.6);
    -webkit-transition: visibility 0.4s linear, opacity 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    transition: visibility 0.4s linear, opacity 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    content: '';
    z-index: 999;
}
main{
    max-width: none;
    display: block;
}
main, .footer--main, .footer-bottom, .page-width {
    margin-left: auto;
    margin-right: auto;
    position: relative;
}
.sub-page-block {
    padding-top: 1.875em;
}
.page-block {
    padding: 3.625em 0;
    border-color: #e5e5e5;
}
@media screen and (min-width: 61.875em){
.page-width {
    width: 85%;
}
.grid-6 {
    width: 700px;
    margin-right: 30px;
}
.sidemenu-column {
    margin-top: 200px;
    padding-bottom: 15px;
    margin-right: -25px;
}
}
.page-width {
    padding-left: 30px;
    padding-right: 30px;
}
.grid-container {
    margin-left: auto;
    margin-right: auto;
    position: relative;
}
.grid-item {
    float: left;
    position: relative;
}
.sidemenu-menu {
    margin: 0;
    line-height: 1.2;
    max-width: 280px;
}
.in-page-menu {
    list-style: none;
    margin-bottom: 30px;
}
.sidemenu-menu__item {
    padding: 7.5px 10px;
}
.sidemenu-menu__item a{
  font-size: 16px;
  display: block;
  line-height: 1.5em;
  text-align: right;
  color: #555;
  text-decoration: none;
}
.sidemenu-menu__item a:hover{
text-decoration: none;
  color: #09afdf;
}
.sidemenu-menu__item a.active{
text-decoration: none;
  color: #09afdf;
}
#content {
    margin-top: 15px;
}
.article.marketing-markdown {
    margin-top: 0;
    padding-bottom: 0;
}
main .marketing-markdown{
    margin-bottom: 0.9375em;
    line-height: 1.5em;
    font-size: 1em;
}
.marketing-markdown {
    margin-top: 10px;
    padding-bottom: 10px;
    color: #444;
}

p, .marketing-markdown, ul, ol {
    margin: 0;
    padding: 0;
}
.article .img-wrapper {
    background: #fff;
    padding: 0;
    margin: 1.875em 0;
    text-align: center;
}
.article .img-wrapper img {
    margin: 0;
}
.marketing-markdown p, .marketing-markdown .marketing-markdown, .marketing-markdown ul, .marketing-markdown ol {
    margin-bottom: 1.25em;
}
.sidemenu-nav-header{
  margin: 0 0 8px 0;
  padding: 0 0 12px 0;
  display: block;
  font-size: 22px;
  border-bottom: 1px solid #ddd;
  color: #6F7479;
  position: relative;
  text-align: right;
  padding-left: 20px;
  min-width: 200px;
  }          /* the head */
  .post-details {
    margin-bottom: 5px;
    color: #a8a8a8;
    font-size: 14px;
    width: 100%;
    float: right;
    padding-right: 3px;
}
</style>